# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta3
kind: Config
build:
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - context: .
      image: example-svc
  tagPolicy:
    sha256: {}
# defines the Kubernetes manifests to deploy on each run
manifests:
  rawYaml:
    - kubernetes/**
deploy:
  kubectl: {}
# use the cloudbuild profile to build images using Google Cloud Build
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: minikube-profile
  activation:
    - kubeContext: minikube
  build:
    artifacts:
    - image: example-svc
      docker:
        dockerfile: Dockerfile
  manifests:
    rawYaml:
      - kubernetes/deployment.yaml
      - kubernetes/service.yaml
  deploy:
    kubectl: {}
- name: staging-profile
  activation:
    - kubeContext: gateway-api
  build:
    artifacts:
    - image: example-svc
      docker:
        dockerfile: Dockerfile
  manifests:
    rawYaml:
      - kubernetes/deployment.yaml
      - kubernetes/service.yaml
      - kubernetes/http-route.yaml
      - kubernetes/external-lb-policy.yaml
  deploy:
    kubectl: {}
