# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - context: src
    image: example-svc
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - kubernetes/**
# use the cloudbuild profile to build images using Google Cloud Build
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: minikube-profile
  activation:
    - kubeContext: minikube
  build:
    artifacts:
    - image: example-svc
      docker:
        dockerfile: Dockerfile
  deploy:
    kubectl:
      manifests:
      - kubernetes/deployment.yaml
      - kubernetes/service.yaml
- name: staging-profile
  activation:
    - kubeContext: staging
  build:
    artifacts:
    - image: example-svc
      docker:
        dockerfile: Dockerfile
  deploy:
    kubectl:
      manifests:
      - kubernetes/deployment.yaml
      - kubernetes/service.yaml
