apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
    - context: .
      image: blue
  tagPolicy:
    sha256: {}
test:
  - image: blue
    context: .
    custom:
      - command: tox -- microservices/blue/tests/test_blue.py
manifests:
  rawYaml:
    - ../../kubernetes/blue/namespace.yaml
    - ../../kubernetes/blue/deployment.yaml
    - ../../kubernetes/blue/service.yaml
deploy:
  kubectl: {}
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: minikube-profile
  activation:
    - kubeContext: minikube
  build:
    artifacts:
    - image: blue
      docker:
        dockerfile: Dockerfile
  portForward:
  - resourceType: deployment
    resourceName: blue
    namespace: blue
    port: 5001
    localPort: 5001
  - resourceType: service
    resourceName: blue
    namespace: blue
    port: 8081
    localPort: 8081
  manifests:
    rawYaml:
      - ../../kubernetes/blue/namespace.yaml
      - ../../kubernetes/blue/deployment.yaml
      - ../../kubernetes/blue/service.yaml
  deploy:
    kubectl: {}
- name: staging-profile
  activation:
    - kubeContext: gateway-api
  build:
    artifacts:
    - image: blue
      docker:
        dockerfile: Dockerfile
  manifests:
    rawYaml:
      - ../../kubernetes/blue/namespace.yaml
      - ../../kubernetes/blue/deployment.yaml
      - ../../kubernetes/blue/service.yaml
  deploy:
    kubectl: {}
