apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
    - context: .
      image: green
  tagPolicy:
    sha256: {}
test:
  - image: green
    context: .
    custom:
      - command: tox -- microservices/green/tests/test_green.py
manifests:
  rawYaml:
    - ../../kubernetes/green/namespace.yaml
    - ../../kubernetes/green/deployment.yaml
    - ../../kubernetes/green/service.yaml
deploy:
  kubectl: {}
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: minikube-profile
  activation:
    - kubeContext: minikube
  build:
    artifacts:
    - image: green
      docker:
        dockerfile: Dockerfile
  portForward:
  - resourceType: deployment
    resourceName: green
    namespace: green
    port: 5002
    localPort: 5002
  - resourceType: service
    resourceName: green
    namespace: green
    port: 8082
    localPort: 8082
  manifests:
    rawYaml:
      - ../../kubernetes/green/namespace.yaml
      - ../../kubernetes/green/deployment.yaml
      - ../../kubernetes/green/service.yaml
  deploy:
    kubectl: {}
- name: staging-profile
  activation:
    - kubeContext: gateway-api
  build:
    artifacts:
    - image: green
      docker:
        dockerfile: Dockerfile
  manifests:
    rawYaml:
      - ../../kubernetes/green/namespace.yaml
      - ../../kubernetes/green/deployment.yaml
      - ../../kubernetes/green/service.yaml
  deploy:
    kubectl: {}
