apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
    - context: .
      image: green
  tagPolicy:
    sha256: {}
manifests:
  rawYaml:
    - ../../kubernetes/deployment-green.yaml
    - ../../kubernetes/service-green.yaml
deploy:
  kubectl: {}
# use the cloudbuild profile to build images using Google Cloud Build
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
- name: minikube-profile
  activation:
    - kubeContext: minikube
  build:
    artifacts:
    - image: green
      docker:
        dockerfile: Dockerfile
  manifests:
    rawYaml:
      - ../../kubernetes/deployment-green.yaml
      - ../../kubernetes/service-green.yaml
  deploy:
    kubectl: {}
- name: staging-profile
  activation:
    - kubeContext: gateway-api
  build:
    artifacts:
    - image: green
      docker:
        dockerfile: Dockerfile
  manifests:
    rawYaml:
      - ../../kubernetes/deployment-green.yaml
      - ../../kubernetes/service-green.yaml
  deploy:
    kubectl: {}
